// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2 , the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

let current = 0;
let next = 1;
const limit = 4000000;
let sum = 0;
let temp = 0;

while (next < limit) {
    temp = 0;
    temp = current + next;
    current = next;
    next = temp;

    if (next < limit && next % 2 === 0) sum += next;
}

console.log(sum);
