// The sequence of triangle numbers is generated by adding the natural numbers. So the th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be: 1, 3, 6, 10, 15, 21, 28, 36, 45, 55.
// Let us list the factors of the first seven triangle numbers:  1: 1 | 3 : 1, 3 | .....
// We can see that  is the first triangle number to have over five divisors.
// What is the value of the first triangle number to have over five hundred divisors?

const getNoOfDivisor = (dividend) => {
    let count = 0;
    for (let divisor = 2; divisor <= Math.sqrt(dividend); divisor++) {
        if (dividend % divisor === 0) {
            count++;
        }
    }
    count += count;
    count += 2;
    return count;
};

const firstTriangleNumberWithDivisorLimit = (limit) => {
    let noOfDivisor = 1;
    let dividend = 1;
    let counter = 2;
    while (noOfDivisor < limit) {
        dividend += counter;
        counter++;

        noOfDivisor = getNoOfDivisor(dividend);
    }
    return dividend;
};

console.log(firstTriangleNumberWithDivisorLimit(500));
